export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const GET_PROJECT_TASKS = 'GET_PROJECT_TASKS';
export const GET_PROJECT_TASK = 'GET_PROJECT_TASK';
export const CREATE_PROJECT_TASK = 'CREATE_PROJECT_TASK';
export const UPDATE_PROJECT_TASK = 'UPDATE_PROJECT_TASK';
export const DELETE_PROJECT_TASK = 'DELETE_PROJECT_TASK';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_COMMENT = 'GET_COMMENT';

export const ADD_ATTACHMENTS = 'ADD_ATTACHMENTS';
export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT';
export const GET_ALL_ATTACHMENTS = 'GET_ALL_ATTACHMENTS';
export const DOWNLOAD_ATTACHMENT = 'DOWNLOAD_ATTACHMENT';

export const ADD_PROJECT_MEMBER = 'ADD_PROJECT_MEMBER'
export const REMOVE_PROJECT_MEMBER = 'REMOVE_PROJECT_MEMBER'
export const LIST_PROJECT_MEMBERS = 'LIST_PROJECT_MEMBERS'

export const LOGIN = 'LOGIN';
export const LOG_OUT = 'LOG_OUT';
export const REGISTER = 'REGISTER';